-- Supabase Schema for Analytics & Transactions
-- Run this in the Supabase SQL editor.

create extension if not exists pgcrypto;

-- 1. Create a table for Products (Master Data)
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  brand text not null,
  supplier text,
  price numeric not null default 0,
  stock int not null default 0, -- Used for 'Out of Stock' / 'Low Stock' calculation
  rating numeric default 0,
  created_at timestamptz not null default now()
);

-- 2. Create a table for Transactions / Orders
create table if not exists public.transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id), -- If orders are tied to a user
  total_price numeric not null default 0,
  total_profit numeric not null default 0, -- Calculated profit from the transaction
  status text not null default 'completed',
  created_at timestamptz not null default now() -- This will be used for time dimensions (Day/Month/Year)
);

-- 3. Create a table for Transaction Details (Items Sold)
create table if not exists public.transaction_items (
  id uuid primary key default gen_random_uuid(),
  transaction_id uuid references public.transactions(id) on delete cascade,
  product_id bigint references public.products(id),
  quantity int not null default 1,
  price_at_purchase numeric not null,
  profit_at_purchase numeric not null,
  created_at timestamptz not null default now()
);

-- Enable RLS
alter table public.products enable row level security;
alter table public.transactions enable row level security;
alter table public.transaction_items enable row level security;

-- Basic Policies (Adjust according to your exact security needs)
create policy "Products are viewable by everyone" on public.products for select using (true);
create policy "Users can view their own transactions" on public.transactions for select using (auth.uid() = user_id);
create policy "Users can view their transaction items" on public.transaction_items for select using (
  exists (select 1 from public.transactions t where t.id = transaction_items.transaction_id and t.user_id = auth.uid())
);
