name: Update Harga Pasar (Setiap 3 Hari)

on:
  schedule:
    # Format Cron: Menit(0) Jam(0) Hari(Setiap kelipatan 3) Bulan(*) HariDalamSeminggu(*)
    - cron: '0 0 */3 * *' 
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
    - name: Ambil kode dari repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install System Dependencies untuk OCR
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr tesseract-ocr-ind

    - name: Install Python Dependencies
      run: |
        pip install -r backend_scraper/requirements.txt

    - name: Jalankan Skrip Crawler
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      run: python backend_scraper/crawler.py